### ISSUE TITLE
extract.py throws SyntaxError

### ISSUE THREAD

**Issue by Markcanfly** [simonwongwong/Facebook-Messenger-Statistics#1]
When trying to run extract.py I get this error:
`$ python extract.py
  File "extract.py", line 12
    files = [x for x in files if not ".py" in x]
        ^
SyntaxError: invalid syntax`

**Comment by simonwongwong** [comment]
sorry, I noticed the problem a couple of days ago and fixed it but forgot to push to master.

should be fixed in the latest [commit](https://github.com/simonwongwong/Facebook-Messenger-Statistics/commit/9e9edbaab5de7a87df98b477ee34f915456fa1cf)

also, try using the new [branch](https://github.com/simonwongwong/Facebook-Messenger-Statistics/tree/refactor_with_pandas), it might have fewer errors
